### ISSUE TITLE
StickyForm

### ISSUE THREAD

**Issue by DolleDries** [dbohdan/HTMLgen#1]
I have:
import StickyForm 

EditForm = StickyForm.StickyForm(target="_self", cgi="%s.py" % (base), submit=DoItButton, state="./%s.state" % (base))

streetBut = HTMLgen.Input(type="text", name='to_street', id='street', value='')

EditForm.with_state( streetBut )
EditForm.append( streetBut )

I find this confusing. I it possible to make a decorator append function that does both the 'with_state' and 'append' stuff?

**Comment by dbohdan** [comment]
Sorry, but I can't help you with this. I do not maintain HTMLgen — this is just a mirror — and I haven't used its form features. If you are working a new project, you may want to try [WTForms](https://wtforms.readthedocs.io/en/stable/) instead.
